import AuthProvider from '@/AuthProvider/AuthProvider'
import { Inter } from 'next/font/google'
import './globals.css'
<<<<<<< HEAD
=======
import AuthProvider from '@/AuthProvider/AuthProvider'
>>>>>>> 8752d2ac7017c1e6d46240f38857b3fb8f947c83

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Book Binimoy',
  description: 'A book exchange and buy-sell platform',
<<<<<<< HEAD
  title: 'Create Next App',
  description: 'Generated by create next app',
=======
>>>>>>> 8752d2ac7017c1e6d46240f38857b3fb8f947c83
}

export default function RootLayout({ children }) {
  return (
<<<<<<< HEAD

=======
>>>>>>> 8752d2ac7017c1e6d46240f38857b3fb8f947c83
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
