import { Inter } from 'next/font/google'
import './globals.css'
<<<<<<< HEAD
=======
import AuthProvider from '@/AuthProvider/AuthProvider'
>>>>>>> 87f6159f830c0cccd1644332b7b9929d72b7e806

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
<<<<<<< HEAD
  title: 'Book Binimoy',
  description: 'A book exchange and buy-sell platform',
=======
  title: 'Create Next App',
  description: 'Generated by create next app',
>>>>>>> 87f6159f830c0cccd1644332b7b9929d72b7e806
}

export default function RootLayout({ children }) {
  return (
<<<<<<< HEAD
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        {children}</body>
=======
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          {children}
        </AuthProvider>


      </body>
>>>>>>> 87f6159f830c0cccd1644332b7b9929d72b7e806
    </html>
  )
}
